In [200]:
import numpy as np 
import pandas as pd 
import os
from pathlib import Path

In [201]:
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/hacker-earth-ds-hiring/dataset/sample_submission.csv
/kaggle/input/hacker-earth-ds-hiring/dataset/train.csv
/kaggle/input/hacker-earth-ds-hiring/dataset/test.csv

# Load Data

In [202]:
df_dict = {}
df_all = pd.DataFrame()
data_dir = Path( '/kaggle/input/hacker-earth-ds-hiring/dataset/')
def read_data(data_dir: Path):
    for file in data_dir.glob("*.csv"):
        df_name = str(file.name).split('.')[0]
        df_ = pd.read_csv(file)
        df_dict[df_name] = df_
    print(f"No. of files read: {len(df_dict)}")
read_data( data_dir)

No. of files read: 3

In [203]:
#files name
df_dict.keys()

dict_keys(['sample_submission', 'train', 'test'])

In [204]:
df_sub = df_dict.pop('sample_submission')

def get_nunique( df_dict= df_dict):
    global df_all
    for key in df_dict.keys():
        print(key, "No. of columns:",  len( df_dict[key].columns ) )
        df_dict[key]['label'] = key
        df_all = df_all.append( df_dict[key] , ignore_index=True)
    print( "total rows:", df_all.shape[0])
get_nunique()

train No. of columns: 24
test No. of columns: 23
total rows: 50000

In [205]:
def fix_columnnames(df_all =df_all):
    columns = [ str(col).replace(' ', '_').replace( '(', '').replace(')', '')
               for col in df_all.columns.to_list()]
    df_all.columns = columns
fix_columnnames()

In [206]:
def get_unique_count( df_all= df_all):
    train = df_all[ df_all['label'] == 'train'] 
    test = df_all[df_all['label'] == 'test']
    for col in train.columns.to_list():
        print( f"train {col} unique values--> {train[col].nunique()} || test {col} unique values--> {test[col].nunique()}")
get_unique_count()

train Customer_ID unique values--> 30000 || test Customer_ID unique values--> 20000
train Name unique values--> 30000 || test Name unique values--> 20000
train Gender unique values--> 2 || test Gender unique values--> 2
train Age unique values--> 48 || test Age unique values--> 48
train Income_USD unique values--> 24429 || test Income_USD unique values--> 18693
train Income_Stability unique values--> 2 || test Income_Stability unique values--> 2
train Profession unique values--> 8 || test Profession unique values--> 7
train Type_of_Employment unique values--> 18 || test Type_of_Employment unique values--> 18
train Location unique values--> 3 || test Location unique values--> 3
train Loan_Amount_Request_USD unique values--> 29982 || test Loan_Amount_Request_USD unique values--> 19988
train Current_Loan_Expenses_USD unique values--> 24041 || test Current_Loan_Expenses_USD unique values--> 17247
train Expense_Type_1 unique values--> 2 || test Expense_Type_1 unique values--> 2
train Expense_Type_2 unique values--> 2 || test Expense_Type_2 unique values--> 2
train Dependents unique values--> 10 || test Dependents unique values--> 10
train Credit_Score unique values--> 17586 || test Credit_Score unique values--> 13756
train No._of_Defaults unique values--> 2 || test No._of_Defaults unique values--> 2
train Has_Active_Credit_Card unique values--> 3 || test Has_Active_Credit_Card unique values--> 3
train Property_ID unique values--> 999 || test Property_ID unique values--> 999
train Property_Age unique values--> 24179 || test Property_Age unique values--> 18560
train Property_Type unique values--> 4 || test Property_Type unique values--> 4
train Property_Location unique values--> 3 || test Property_Location unique values--> 3
train Co-Applicant unique values--> 3 || test Co-Applicant unique values--> 3
train Property_Price unique values--> 29632 || test Property_Price unique values--> 19824
train Loan_Sanction_Amount_USD unique values--> 21450 || test Loan_Sanction_Amount_USD unique values--> 0
train label unique values--> 1 || test label unique values--> 1